package prosense.sassa.pipclient;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "PersonIdentityProfileResponseError", targetNamespace = "http://ijs.gov.za/schemas/messages/PersonIdentityProfile/ResponseError/1.0")
public class PersonIdentiyServiceOpPersonIdentiyServiceErrorMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PersonIdentityProfileResponseError faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public PersonIdentiyServiceOpPersonIdentiyServiceErrorMessage(String message, PersonIdentityProfileResponseError faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public PersonIdentiyServiceOpPersonIdentiyServiceErrorMessage(String message, PersonIdentityProfileResponseError faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: prosense.sassa.pipclient1.PersonIdentityProfileResponseError
     */
    public PersonIdentityProfileResponseError getFaultInfo() {
        return faultInfo;
    }

}
