package prosense.sassa.pipclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonIdentiyService", targetNamespace = "http://tempuri.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonIdentiyService {


    /**
     * 
     * @param part
     * @return
     *     returns prosense.sassa.pipclient1.PersonIdentityProfileResponse
     * @throws PersonIdentiyServiceOpPersonIdentiyServiceErrorMessage
     */
    @WebMethod(action = "opPersonIdentiyService")
    @WebResult(name = "PersonIdentityProfileResponse", targetNamespace = "http://ijs.gov.za/schemas/messages/PersonIdentityProfile/Response/1.0", partName = "part")
    public PersonIdentityProfileResponse opPersonIdentiyService(
        @WebParam(name = "PersonIdentityProfileRequest", targetNamespace = "http://ijs.gov.za/schemas/messages/PersonIdentityProfile/Request/1.0", partName = "part")
        PersonIdentityProfileRequest part)
        throws PersonIdentiyServiceOpPersonIdentiyServiceErrorMessage
    ;

}
